import type { StringInput } from '../types';
import { normalizeStringInput } from './normalize-string-input';

type EmptyString = '';
type EmailString = `${string}@${string}`;
type WrongDomain = string;

export enum EmailDomains {
  GMAIL = 'gmail.com',
  HOTMAIL = 'hotmail.com',
  OUTLOOK = 'outlook.com',
  PROTONMAIL = 'protonmail.com',
  YAHOO = 'yahoo.com',
  ZIPMAIL = 'zipmail.com.br',
  BOL = 'bol.com.br',
}

const wrongEmailDomainsRecord: Record<WrongDomain, EmailDomains> =
  getWrongEmailDomainsRecord();

export function suggestEmail(
  typedEmail: StringInput = '',
): EmptyString | EmailString {
  const [user, domain] = normalizeStringInput(typedEmail).split('@');
  const correctDomain = domain ? wrongEmailDomainsRecord[domain] : undefined;
  return correctDomain ? `${user}@${correctDomain}` : '';
}

function getWrongEmailDomainsRecord(): Record<WrongDomain, EmailDomains> {
  return {
    'bol.com': EmailDomains.BOL,
    'dmail.com': EmailDomains.GMAIL,
    'gail.com': EmailDomains.GMAIL,
    'gail.com.ar': EmailDomains.GMAIL,
    'gamail.com': EmailDomains.GMAIL,
    'gamail.com.ar': EmailDomains.GMAIL,
    'gamial.com': EmailDomains.GMAIL,
    'gamial.com.ar': EmailDomains.GMAIL,
    'gamil.com': EmailDomains.GMAIL,
    'gamil.com.ar': EmailDomains.GMAIL,
    'gemail.com': EmailDomains.GMAIL,
    'ggmail.com': EmailDomains.GMAIL,
    'ggmail.com.ar': EmailDomains.GMAIL,
    'gil.com': EmailDomains.GMAIL,
    'gimail.com': EmailDomains.GMAIL,
    'gmad.com,': EmailDomains.GMAIL,
    'gmai.com': EmailDomains.GMAIL,
    'gmai.com.ar': EmailDomains.GMAIL,
    'gmaiil.com': EmailDomains.GMAIL,
    'gmaiil.com.ar': EmailDomains.GMAIL,
    gmail: EmailDomains.GMAIL,
    'gmail.': EmailDomains.GMAIL,
    'gmail.c': EmailDomains.GMAIL,
    'gmail.cim': EmailDomains.GMAIL,
    'gmail.cin': EmailDomains.GMAIL,
    'gmail.cm': EmailDomains.GMAIL,
    'gmail.cm.ar': EmailDomains.GMAIL,
    'gmail.cm.br': EmailDomains.GMAIL,
    'gmail.co': EmailDomains.GMAIL,
    'gmail.cok': EmailDomains.GMAIL,
    'gmail.com.': EmailDomains.GMAIL,
    'gmail.com.ar': EmailDomains.GMAIL,
    'gmail.com.b': EmailDomains.GMAIL,
    'gmail.com.br': EmailDomains.GMAIL,
    'gmail.comm': EmailDomains.GMAIL,
    'gmail.con': EmailDomains.GMAIL,
    'gmail.coom': EmailDomains.GMAIL,
    'gmail.cpm': EmailDomains.GMAIL,
    'gmailc.mo': EmailDomains.GMAIL,
    'gmailc.om': EmailDomains.GMAIL,
    'gmaild.com': EmailDomains.GMAIL,
    'gmaild.com.ar': EmailDomains.GMAIL,
    'gmaile.com': EmailDomains.GMAIL,
    'gmaile.com.ar': EmailDomains.GMAIL,
    'gmailee.com': EmailDomains.GMAIL,
    'gmaill.com': EmailDomains.GMAIL,
    'gmaill.com.ar': EmailDomains.GMAIL,
    'gmain.com': EmailDomains.GMAIL,
    'gmain.com.ar': EmailDomains.GMAIL,
    'gmaio.com': EmailDomains.GMAIL,
    'gmaio.com.ar': EmailDomains.GMAIL,
    'gmaiq.com': EmailDomains.GMAIL,
    'gmakl.com': EmailDomains.GMAIL,
    'gmal.com': EmailDomains.GMAIL,
    'gmal.com.ar': EmailDomains.GMAIL,
    'gmali.com': EmailDomains.GMAIL,
    'gmali.com.ar': EmailDomains.GMAIL,
    'gmanil.com': EmailDomains.GMAIL,
    'gmanil.com.ar': EmailDomains.GMAIL,
    'gmaol.com': EmailDomains.GMAIL,
    'gmaol.com.ar': EmailDomains.GMAIL,
    'gmaqil.com': EmailDomains.GMAIL,
    'gmaqil.com.ar': EmailDomains.GMAIL,
    'gmaul.com': EmailDomains.GMAIL,
    'gmeil.com': EmailDomains.GMAIL,
    'gmeil.com.ar': EmailDomains.GMAIL,
    'gmiail.com': EmailDomains.GMAIL,
    'gmial.com': EmailDomains.GMAIL,
    'gmial.com.ar': EmailDomains.GMAIL,
    'gmil.co': EmailDomains.GMAIL,
    'gmil.com': EmailDomains.GMAIL,
    'gmil.com.ar': EmailDomains.GMAIL,
    'gmmail.com': EmailDomains.GMAIL,
    'gmmail.com.ar': EmailDomains.GMAIL,
    'gmnail.com': EmailDomains.GMAIL,
    'gmol.com': EmailDomains.GMAIL,
    'gmsil.com': EmailDomains.GMAIL,
    'gmsil.com.ar': EmailDomains.GMAIL,
    'gnail.com': EmailDomains.GMAIL,
    'hatmail.com': EmailDomains.HOTMAIL,
    'hitmail.com': EmailDomains.HOTMAIL,
    'hmail.com': EmailDomains.HOTMAIL,
    'hmail.com.ar': EmailDomains.HOTMAIL,
    'hoimail.com': EmailDomains.HOTMAIL,
    'hoitmail.com': EmailDomains.HOTMAIL,
    'homail.com': EmailDomains.HOTMAIL,
    'homtail.com': EmailDomains.HOTMAIL,
    'homtmail.com': EmailDomains.HOTMAIL,
    'hootmail.com': EmailDomains.HOTMAIL,
    'hormail.com': EmailDomains.HOTMAIL,
    'hotail.com': EmailDomains.HOTMAIL,
    'hotamail.com': EmailDomains.HOTMAIL,
    'hotamil.com': EmailDomains.HOTMAIL,
    'hotma.com': EmailDomains.HOTMAIL,
    'hotmaail.com': EmailDomains.HOTMAIL,
    'hotmai.com': EmailDomains.HOTMAIL,
    'hotmaiil.com': EmailDomains.HOTMAIL,
    'hotmail.cim': EmailDomains.HOTMAIL,
    'hotmail.cin': EmailDomains.HOTMAIL,
    'hotmail.cm': EmailDomains.HOTMAIL,
    'hotmail.co': EmailDomains.HOTMAIL,
    'hotmail.com.com': EmailDomains.HOTMAIL,
    'hotmail.comm': EmailDomains.HOTMAIL,
    'hotmail.con': EmailDomains.HOTMAIL,
    'hotmail.coom': EmailDomains.HOTMAIL,
    'hotmail.net': EmailDomains.HOTMAIL,
    'hotmail.ocm': EmailDomains.HOTMAIL,
    'hotmaill.com': EmailDomains.HOTMAIL,
    'hotmailt.com': EmailDomains.HOTMAIL,
    'hotmal.com': EmailDomains.HOTMAIL,
    'hotmali.com': EmailDomains.HOTMAIL,
    'hotmi.com': EmailDomains.HOTMAIL,
    'hotmiail.com': EmailDomains.HOTMAIL,
    'hotmial.com': EmailDomains.HOTMAIL,
    'hotmil.co': EmailDomains.HOTMAIL,
    'hotmil.com': EmailDomains.HOTMAIL,
    'hotmmail.com': EmailDomains.HOTMAIL,
    'hotmqil.com': EmailDomains.HOTMAIL,
    'hotmsil.com': EmailDomains.HOTMAIL,
    'hotnail.ckm': EmailDomains.HOTMAIL,
    'hotnail.com': EmailDomains.HOTMAIL,
    'hotomail.com': EmailDomains.HOTMAIL,
    'hotrmail.com': EmailDomains.HOTMAIL,
    'hoymail.com': EmailDomains.HOTMAIL,
    'htmail.com': EmailDomains.HOTMAIL,
    'htoamil.com': EmailDomains.HOTMAIL,
    'htomail.com': EmailDomains.HOTMAIL,
    'mail.com': EmailDomains.GMAIL,
    'mgil.com': EmailDomains.GMAIL,
    'otmail.com': EmailDomains.HOTMAIL,
    'outlok.com': EmailDomains.OUTLOOK,
    'outloo.com': EmailDomains.OUTLOOK,
    'outlook.cm': EmailDomains.OUTLOOK,
    'outlook.co': EmailDomains.OUTLOOK,
    'outlook.comm': EmailDomains.OUTLOOK,
    'outlook.con': EmailDomains.OUTLOOK,
    'prontomail.com': EmailDomains.PROTONMAIL,
    'protonmil.com': EmailDomains.PROTONMAIL,
    'yaho.com': EmailDomains.YAHOO,
    'yahoo.comm': EmailDomains.YAHOO,
    'yahoo.con': EmailDomains.YAHOO,
    'yahoo.coom': EmailDomains.YAHOO,
    'ygmail.com': EmailDomains.GMAIL,
    'ygmail.com.ar': EmailDomains.GMAIL,
    'zipmail.combr': EmailDomains.ZIPMAIL,
  };
}
